name: Release Multi-Target

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: .exe
          - target: x86_64-apple-darwin
            os: macos-latest
            ext: ""

    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release -p uhdr2avif --target ${{ matrix.target }}

      - name: Rename and prepare binary
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/uhdr2avif${{ matrix.ext }} dist/uhdr2avif-${{ matrix.target }}${{ matrix.ext }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/uhdr2avif-${{ matrix.target }}${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
